print("strings intro")
s="codegnan"
print(s[0])
print(s[1])
print(s[2])
print(s[3])
print(s[4])
print(s[5])
print(s[6])
print(s[7])
print(s[1:5:1])
print(s[8:10])
print(s[-1:5])
print(s[-2:-6:-1])
print(s[:8])
print(s[::-1])
print(s[:-5:-1])
print(s[::])
print(s[:4]+"z"+s[5:8])

